const express = require('express');
const router = express.Router();
const serviceController = require('../controllers/serviceController');
const adminController   = require('../controllers/adminController');
const verifyAdmin = require('../middlewares/authMiddleware');
router.post('/users/register', adminController.register);
router.post('/users/login', adminController.login);
router.get('/appointments/user/:userId', serviceController.getMyAppointments);
router.post('/login', adminController.login);
router.get('/services', serviceController.getAllServices);
router.get('/services/:id', serviceController.getServiceById);
router.post('/appointments', serviceController.createAppointment);
router.post  ('/admin/services', verifyAdmin, adminController.createService);
router.put   ('/admin/services/:id', verifyAdmin, adminController.updateService);
router.delete('/admin/services/:id', verifyAdmin, adminController.deleteService);
router.get   ('/admin/users', verifyAdmin, adminController.getAllUsers);
router.delete('/admin/users/:id', verifyAdmin, adminController.deleteUser);
router.get   ('/admin/appointments', verifyAdmin, adminController.getAllAppointments);
router.put   ('/admin/appointments/:id/status', verifyAdmin, adminController.updateAppointmentStatus);
router.delete('/admin/appointments/:id', verifyAdmin, adminController.deleteAppointment);
module.exports = router;